[package]
name = "pgb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
panic = "abort"
strip = true
lto = true
incremental = false

[dependencies]
gba = "0.10.1"
